### ISSUE TITLE
SIGSEGV: invalid_state

### ISSUE THREAD

**Issue by Dellos7** [Ninjaclasher/dmoj-docker#12]
Hello,
I've followed the steps in the README and when I try to open de site in my browser I get the following error message:

```
SIGSEGV: invalid_state

corrupt page /
site: fatal signal: Segmentation fault
site died (signal 500, exit -11)

panic: [go back](javascript:history.back())
```

Then, in the nginx error.log file there's this message:
`2023/03/19 12:48:17 [error] 20#20: *1 directory index of "/assets/resources/icons/" is forbidden, client: 10.0.2.15, server: 10.0.2.15, request: "GET / HTTP/1.1", host: "10.0.2.15"`

I'm not expert in nginx and I don't know Django. Please can you help me o guide me in order to solve this issue?

Thank you very much.

**Comment by Ninjaclasher** [comment]
This was an issue with an upstreaming dependency introducing a hard dependency (https://github.com/python-social-auth/social-core/pull/590#issuecomment-1471631500). I've pulled the latest changes (https://github.com/DMOJ/online-judge/pull/2248) in 18710f4855a9cbab0709bbb148f8966f7b8ba806. Let me know if it fixes the issue.

**Comment by Dellos7** [comment]
Thank you very much @Ninjaclasher , it worked!
