### ISSUE TITLE
No judge is available for this problem.

### ISSUE THREAD

**Issue by excel-azmin** [Ninjaclasher/dmoj-docker#16]
I have follow this [documentation](https://github.com/Ninjaclasher/dmoj-docker) the installation part work properly but I'm unable to submit the code due to `No Judge` issue. 
![image](https://github.com/Ninjaclasher/dmoj-docker/assets/92359442/6e3b5ea8-1d01-46eb-b4bf-0a11afc8124b)

Then I have create new `judge` but by default is disabled. 

![image](https://github.com/Ninjaclasher/dmoj-docker/assets/92359442/b536bf88-e2c4-4e62-8c70-5c25ba5be785)

How do we create judge to submit the problem. 

Thanks

**Comment by yanngv29** [comment]
You need to add a judge using this documentation : 
[https://docs.dmoj.ca/#/judge/setting_up_a_judge](https://docs.dmoj.ca/#/judge/setting_up_a_judge
)
