### ISSUE TITLE
error when running migrate script

### ISSUE THREAD

**Issue by yanngv29** [Ninjaclasher/dmoj-docker#18]
i run in this error when installing at the "migrate" stage : 

  File "/usr/local/lib/python3.11/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.

i bash into the container and install lxml_html_clean, then it work.

**Comment by Ninjaclasher** [comment]
This should be resolved now.
